package bo.edu.uagrm.ficct.inf310.ed202102.ui.practicos;

import bo.edu.uagrm.ficct.inf310.ed202102.grafos.excepciones.ExcepcionAristaNoExiste;
import bo.edu.uagrm.ficct.inf310.ed202102.grafos.excepciones.ExcepcionAristaYaExiste;
import bo.edu.uagrm.ficct.inf310.ed202102.grafos.excepciones.ExcepcionNumVerticesInvalido;
import bo.edu.uagrm.ficct.inf310.ed202102.grafos.excepciones.ExceptionVerticeNoValido;
import bo.edu.uagrm.ficct.inf310.ed202102.grafos.matrices.no_pesado.MatrizDigrafo;
import bo.edu.uagrm.ficct.inf310.ed202102.grafos.matrices.pesado.MatrizDePredecesores;
import bo.edu.uagrm.ficct.inf310.ed202102.grafos.matrices.pesado.MatrizDigrafoPesado;
import bo.edu.uagrm.ficct.inf310.ed202102.grafos.nopesados.AlgoritmoWarshall;
import bo.edu.uagrm.ficct.inf310.ed202102.grafos.nopesados.Digrafo;
import bo.edu.uagrm.ficct.inf310.ed202102.grafos.nopesados.Grafo;
import bo.edu.uagrm.ficct.inf310.ed202102.grafos.pesados.AlgoritmoDeFloyd;
import bo.edu.uagrm.ficct.inf310.ed202102.grafos.pesados.DigrafoPesado;
import bo.edu.uagrm.ficct.inf310.ed202102.grafos.pesados.GrafoPesado;

import java.util.Scanner;

public class TestPracticoGrafos {
    public static void main(String[] args) throws ExcepcionAristaYaExiste
            , ExcepcionNumVerticesInvalido, ExcepcionAristaNoExiste, ExceptionVerticeNoValido {

        //--------------------------------------------------------------------------------------




//        Scanner entrada3 = new Scanner(System.in);
//        System.out.print("Ingrese el número de vertices para su grafo pesado: ");
//        String nro31 = entrada3.next();
//        int nro32 = Integer.parseInt(nro31);
//        GrafoPesado grafoDePruebaPesado = new GrafoPesado(nro32);

        System.out.println("----------------------------------------------------------------------------------");
        System.out.println("Respuesta al enunciado 1: ");
        System.out.println("Métodos a probar con (grafoDePruebaNoPesado)");
        Grafo grafoDePruebaNoPesado = new Grafo(10);
        grafoDePruebaNoPesado.insertarArista(0, 1);
        grafoDePruebaNoPesado.insertarArista(0, 2);
        grafoDePruebaNoPesado.insertarArista(0, 6);
        grafoDePruebaNoPesado.insertarArista(1, 3);
        grafoDePruebaNoPesado.insertarArista(1, 4);
        grafoDePruebaNoPesado.insertarArista(2, 4);
        grafoDePruebaNoPesado.insertarArista(3, 4);
        grafoDePruebaNoPesado.insertarArista(3, 5);
        grafoDePruebaNoPesado.insertarArista(4, 6);
        grafoDePruebaNoPesado.insertarArista(5, 6);
        grafoDePruebaNoPesado.insertarArista(5, 8);
        grafoDePruebaNoPesado.insertarArista(6, 7);
        grafoDePruebaNoPesado.insertarArista(6, 8);
        grafoDePruebaNoPesado.insertarArista(6, 9);
        System.out.println( "10 vertices insertados");
        System.out.println("Cantidad de aristas en el grafo no pesado: " + grafoDePruebaNoPesado.cantidadDeAristas());
        System.out.println("Grado del vertice 0 en el grafo no pesado: " + grafoDePruebaNoPesado.gradoDeVertice(0));
        System.out.println("Cantidad de vertices en el grafo no pesado: " + grafoDePruebaNoPesado.cantidadDeVertices());
        grafoDePruebaNoPesado.eliminarArista(6,7);
        System.out.println("Arista eliminada: (6, 7)");
        grafoDePruebaNoPesado.eliminarVertice(0);
        System.out.println("Vertice eliminado: 0");
        System.out.println("Cantidad de vertices  despues de eliminar el vertice 0 en el grafo no pesado: " + grafoDePruebaNoPesado.cantidadDeVertices());
        System.out.println("Cantidad de aristas despues de eliminar el vertice 0 y arista (6, 7) en el grafo no pesado: " + grafoDePruebaNoPesado.cantidadDeAristas());
        System.out.println("----------------------------------------------------------------------------------");
        System.out.println("Respuesta al enunciado 2: ");
        System.out.println("Métodos a probar con (digrafoDePruebaNoPesado)");
        Digrafo digrafoDePruebaNoPesado = new Digrafo(10);
        digrafoDePruebaNoPesado.insertarArista(0, 1);
        digrafoDePruebaNoPesado.insertarArista(0, 2);
        digrafoDePruebaNoPesado.insertarArista(0, 6);
        digrafoDePruebaNoPesado.insertarArista(1, 3);
        digrafoDePruebaNoPesado.insertarArista(2, 4);
        digrafoDePruebaNoPesado.insertarArista(3, 4);
        digrafoDePruebaNoPesado.insertarArista(4, 1);
        digrafoDePruebaNoPesado.insertarArista(5, 3);
        digrafoDePruebaNoPesado.insertarArista(5, 6);
        digrafoDePruebaNoPesado.insertarArista(6, 4);
        digrafoDePruebaNoPesado.insertarArista(6, 7);
        digrafoDePruebaNoPesado.insertarArista(6, 8);
        digrafoDePruebaNoPesado.insertarArista(8, 5);
        digrafoDePruebaNoPesado.insertarArista(9, 6);
        System.out.println("10 vertices insertados");
        System.out.println("Cantidad de aristas en el digrafo no pesado: " + digrafoDePruebaNoPesado.cantidadDeAristas());
        System.out.println("Grado de entrada de vertice 6 en el digrafo no pesado: " + digrafoDePruebaNoPesado.gradoDeEntradaDeVertice(6));
        System.out.println("Grado de salida de vertice 6 en el digrafo no pesado: " + digrafoDePruebaNoPesado.gradoDeSalidaDeUnVertice(5));
        System.out.println("Cantidad de vertices en el digrafo no pesado: " + digrafoDePruebaNoPesado.cantidadDeVertices());
        digrafoDePruebaNoPesado.eliminarArista(0,2);
        System.out.println("Arista eliminada: (0, 2)");
        digrafoDePruebaNoPesado.eliminarVertice(6);
        System.out.println("Vertice eliminado: 6");
        System.out.println("Cantidad de vertices  despues de eliminar el vertice 6 en el digrafo no pesado: " + digrafoDePruebaNoPesado.cantidadDeVertices());
        System.out.println("Cantidad de aristas despues de eliminar el vertice 6 y arista (0, 2) en el digrafo no pesado: " + digrafoDePruebaNoPesado.cantidadDeAristas());
        System.out.println("----------------------------------------------------------------------------------");
        System.out.println("Respuesta al enunciado 3: ");
        System.out.println("Método a probar con (digrafoDePruebaNoPesado)");
        System.out.println("Hay ciclo en el digrafo no pesado: " + digrafoDePruebaNoPesado.hayCiclo());
        System.out.println("----------------------------------------------------------------------------------");
        System.out.println("Respuesta al enunciado 4: ");
        System.out.println("Método a probar con (warshallPrueba1)");
        Digrafo digrafoParaMatriz1 = new Digrafo();
        MatrizDigrafo matrizDirigidoPrueba1 = new MatrizDigrafo(5, digrafoParaMatriz1);
        matrizDirigidoPrueba1.insertarArista(0, 1);
        matrizDirigidoPrueba1.insertarArista(1, 4);
        matrizDirigidoPrueba1.insertarArista(1, 3);
        matrizDirigidoPrueba1.insertarArista(3, 1);
        matrizDirigidoPrueba1.insertarArista(4, 2);
        matrizDirigidoPrueba1.insertarArista(2, 4);
        matrizDirigidoPrueba1.insertarArista(2, 2);
        AlgoritmoWarshall warshallPrueba1 = new AlgoritmoWarshall(matrizDirigidoPrueba1);
        warshallPrueba1.procesarAlgoritmoWarshall();
        System.out.println("Hay ciclo en el digrafo no pesado, con matriz de camino(precondicion: algoritmo de warshall procesado): "
                + warshallPrueba1.hayCiclo());
        System.out.println("----------------------------------------------------------------------------------");
        System.out.println("Respuesta al enunciado 5: ");
        System.out.println("Método a probar con (digrafoDePruebaNoPesado2)");
        Digrafo digrafoDePruebaNoPesado2 = new Digrafo(7);
        digrafoDePruebaNoPesado2.insertarArista(0, 1);
        digrafoDePruebaNoPesado2.insertarArista(2, 0);
        digrafoDePruebaNoPesado2.insertarArista(4, 5);
        digrafoDePruebaNoPesado2.insertarArista(5, 4);
        digrafoDePruebaNoPesado2.insertarArista(6, 4);
        digrafoDePruebaNoPesado2.componentesDeLasIslasDeUnDigrafo();

        System.out.println("----------------------------------------------------------------------------------");
        System.out.println("Respuesta al enunciado 6: ");
        System.out.println("Método a probar con (matrizDigrafoPrueba2)");
        Digrafo digrafoParaMatriz2 = new Digrafo();
        MatrizDigrafo matrizDigrafoPrueba2 = new MatrizDigrafo(5, digrafoParaMatriz2);
        matrizDigrafoPrueba2.insertarArista(0, 1);
        matrizDigrafoPrueba2.insertarArista(1, 4);
        matrizDigrafoPrueba2.insertarArista(1, 3);
        matrizDigrafoPrueba2.insertarArista(3, 1);
        matrizDigrafoPrueba2.insertarArista(4, 2);
        matrizDigrafoPrueba2.insertarArista(2, 4);
        matrizDigrafoPrueba2.insertarArista(2, 2);
        System.out.println("Matriz de camino de un digrafo (digrafoParaMatriz2), sin haber procesado el algoritmo de warshall: ");
        matrizDigrafoPrueba2.mostrarMatrizDeAdyacencia();
        System.out.println("----------------------------------------------------------------------------------");
        System.out.println("Respuesta al enunciado 7: ");
        System.out.println("Método a probar con (digrafoDePruebaNoPesado)");
        System.out.println("Es digrafo debilmente conexo: " + digrafoDePruebaNoPesado.esDebilmenteConexo());
        System.out.println("----------------------------------------------------------------------------------");
        System.out.println("Respuesta al enunciado 8: ");
        System.out.println("Método a probar con (digrafoDePruebaNoPesado)");
        System.out.println("Es digrafo fuertemente conexo: " + digrafoDePruebaNoPesado.esFuertementeConexo());
        System.out.println("----------------------------------------------------------------------------------");
        System.out.println("Respuesta al enunciado 9: ");
        System.out.println("Método a probar con (grafoDePruebaNoPesado)");
        System.out.println("Hay ciclo en el grafo no pesado: " + grafoDePruebaNoPesado.hayCiclo());
        System.out.println("----------------------------------------------------------------------------------");
        System.out.println("Respuesta al enunciado 10: ");
        System.out.println("Método a probar con (grafoDePruebaNoPesado1)");
        Grafo grafoDePruebaNoPesado1 = new Grafo(8);
        grafoDePruebaNoPesado1.insertarArista(0, 3);
        grafoDePruebaNoPesado1.insertarArista(2, 0);
        grafoDePruebaNoPesado1.insertarArista(4, 7);
        grafoDePruebaNoPesado1.insertarArista(6, 4);
        grafoDePruebaNoPesado1.componentesDeLasIslasDeUnGrago();
        System.out.println("----------------------------------------------------------------------------------");
        System.out.println("Respuesta al enunciado 11: ");
        System.out.println("Método a probar con (digrafoDePruebaNoPesado)");
        System.out.println("Número de islas que hay en un digrafo no pesado: " + digrafoDePruebaNoPesado.nroDeIslasEnUnDigrafo());
        System.out.println("----------------------------------------------------------------------------------");
        System.out.println("Respuesta al enunciado 12: ");
        System.out.println("Método a probar con (warshallPrueba2)");
        Digrafo digrafoParaMatriz3 = new Digrafo();
        MatrizDigrafo matrizDigrafoPrueba3 = new MatrizDigrafo(5, digrafoParaMatriz3);
        matrizDigrafoPrueba3.insertarArista(0, 1);
        matrizDigrafoPrueba3.insertarArista(1, 4);
        matrizDigrafoPrueba3.insertarArista(1, 3);
        matrizDigrafoPrueba3.insertarArista(3, 1);
        matrizDigrafoPrueba3.insertarArista(4, 2);
        matrizDigrafoPrueba3.insertarArista(2, 4);
        matrizDigrafoPrueba3.insertarArista(2, 2);
        AlgoritmoWarshall warshallPrueba2 = new AlgoritmoWarshall(matrizDigrafoPrueba3);
        warshallPrueba2.procesarAlgoritmoWarshall();
        warshallPrueba2.mostrarMatrizDeCamino();
        System.out.println("Entre que vertices hay camino(Precondicion algoritmo de warshall procesado): ");
        System.out.println("----------------------------------------------------------------------------------");
        System.out.println("Respuesta al enunciado 13: ");
        System.out.println("Método a probar con (floydPrueba)");
        DigrafoPesado digrafoPesadoParaMatriz = new DigrafoPesado();
        MatrizDigrafoPesado matrizPrueba = new MatrizDigrafoPesado(5, digrafoPesadoParaMatriz);
        matrizPrueba.insertarAristaYSuPeso(0,1,1);
        matrizPrueba.insertarAristaYSuPeso(1,3,4);
        matrizPrueba.insertarAristaYSuPeso(1,4,7);
        matrizPrueba.insertarAristaYSuPeso(2,0,3);
        matrizPrueba.insertarAristaYSuPeso(2,1,2);
        matrizPrueba.insertarAristaYSuPeso(2,4,4);
        matrizPrueba.insertarAristaYSuPeso(3,0,6);
        matrizPrueba.insertarAristaYSuPeso(3,4,2);
        matrizPrueba.insertarAristaYSuPeso(4,3,3);
        AlgoritmoDeFloyd floydPrueba = new AlgoritmoDeFloyd(matrizPrueba);
        floydPrueba.procesarAlgoritmoFloyd();
        floydPrueba.caminoDeCostoMinimo(4, 1);
        System.out.println("----------------------------------------------------------------------------------");
        System.out.println("Respuesta al enunciado 14: ");
        System.out.println("----------------------------------------------------------------------------------");
        System.out.println("Respuesta al enunciado 15: ");
        System.out.println("Método a probar con digrafoDePruebaPesado");
        DigrafoPesado digrafoDePruebaPesado = new DigrafoPesado(6);
        //DigrafoPesado digrafoDePruebaPesado = new DigrafoPesado(7);
        digrafoDePruebaPesado.insertarArista(0, 1, 50);
        digrafoDePruebaPesado.insertarArista(0, 2, 10);
        digrafoDePruebaPesado.insertarArista(0, 4, 60);
        digrafoDePruebaPesado.insertarArista(0, 5, 100);
        digrafoDePruebaPesado.insertarArista(1, 3, 50);
        digrafoDePruebaPesado.insertarArista(1, 4, 15);
        digrafoDePruebaPesado.insertarArista(2, 1, 5);
        digrafoDePruebaPesado.insertarArista(3, 0, 80);
        digrafoDePruebaPesado.insertarArista(3, 5, 20);
        digrafoDePruebaPesado.insertarArista(4, 5, 20);
        digrafoDePruebaPesado.insertarArista(5, 1, 40);
        digrafoDePruebaPesado.insertarArista(5, 2, 70);
        digrafoDePruebaPesado.algoritmoDijkstra(0, 5);
        System.out.println("----------------------------------------------------------------------------------");
        System.out.println("Respuesta al enunciado 16: ");
        System.out.println("----------------------------------------------------------------------------------");
        System.out.println("Respuesta al enunciado 17: ");
        System.out.println("----------------------------------------------------------------------------------");
        System.out.println("Respuesta al enunciado 18: ");
        System.out.println("Método a probar con digrafoDePruebaNoPesado1");
        Digrafo digrafoDePruebaNoPesado1 = new Digrafo(5);

        digrafoDePruebaNoPesado1.insertarArista(0, 1);
        digrafoDePruebaNoPesado1.insertarArista(0, 2);
        digrafoDePruebaNoPesado1.insertarArista(0, 3);
        digrafoDePruebaNoPesado1.insertarArista(0, 4);
        digrafoDePruebaNoPesado1.insertarArista(1, 3);
        digrafoDePruebaNoPesado1.insertarArista(2, 1);
        digrafoDePruebaNoPesado1.insertarArista(3, 4);
        System.out.println("Ordenamiento topológico: " + digrafoDePruebaNoPesado1.ordenamientoTopologico());
        System.out.println("----------------------------------------------------------------------------------");
        System.out.println("Respuesta al enunciado 19: ");

        System.out.println("");
    }
}
